/* 
const leapYears = function() {

};

// Do not edit below this line
module.exports = leapYears;
*/

// LEAVE THE ABOVE ALONE. YOUR VERSION OF JEST WILL NOT WORK SO YOU CAN'T DO ANY TEST DRIVEN DEVELOPMENT.
// WHEN YOU GET A NEW COMPUTER, THEN MAKE SURE THE VM, VISUAL STUDIO, NODE, JEST ETC IS THE ONE YOU 
// ARE SUPPOSED TO BE USING. RIGHT NOW, YOUR 32 BIT MACHINE CAN'T USE THE LATER VERSIONS.

